// 🛑 GENERATED BY TILT SDK - DO NOT EDIT
// Source: .tilt/topologies/tilt/resources/orchestrator/generators/frontend.star
// Purpose: Environment constants for inventory resource

/**
 * Base API URL for inventory resource
 * Uses VITE_API_URL env var with fallback to local dev URL
 */
export const API_URL = import.meta.env.VITE_API_URL || 'http://api.tdk-erp-system.localhost/api/inventory-management';
